name: test-action

on:
  push:
    branches:
      - 'master'
  # pull_request:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '.github/**'
  #     - 'devops/**'
  workflow_dispatch:
  
jobs:
  fetch_file:
    runs-on: ubuntu-latest
    steps:

    - name: GIT Checkout
      uses: actions/checkout@v4

    - name: Checkout db backup repo
      uses: actions/checkout@v4
      with:
        repository: jbs1127/test-actions
        path: './test-actions/'

    - name: list files
      run: ls -lR
